language: node_js
node_js:
- "9"
script:
- echo "Deploy"
install:
- npm install -g firebase-tools @angular/cli
- npm install
after_success:
- firebase deploy --project shiny-waffle --token $FIREBASE_TOKEN
